swagger: '2.0'
info:
  version: "1.0.1"
  title: temperatureSensorAPI
  description: A simple API for getting and updating the temperature of a sensor
schemes:
 - https
basePath: /dev
# securityDefinitions:
#   api_key:
#     type: "apiKey"
#     in: header
#     name: "x-api-key"
# security:
#   - api_key: []
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - CORS
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    post:
      description: Adds a new temperature sensor 
      parameters:
        - name: area
          in: body
          description: Name of area where temperature sensor is located (e.g. Main Floor)
          required: true
          schema:
            type: object
            properties:
              area:
                type: string
      responses:
        200:
          description: temperatureSensor device state with uuid
          $ref: '#/responses/headers'
          schema:
            $ref: '#/definitions/State'
        400:
          $ref: '#/responses/Error'
      x-lambda-function: state
    get:
      description: Gives list of temperature sensors
      responses:
        200:
          description: temperature sensors
          $ref: '#/responses/headers'
          schema:
            type: array
            items:
              $ref: '#/definitions/State'
      x-lambda-function: state
        
  /{uuid}:
    options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - CORS
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {
              "statusCode" : 200
            }
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
    get:
      description: Gets the state of a temperature sensor 
      parameters: 
        - $ref: '#/parameters/UUID'
      responses:
        200:
          description: temperature sensor state
          $ref: '#/responses/headers'
          schema:
            $ref: '#/definitions/State'
        400:
          $ref: '#/responses/Error'
      x-lambda-function: state

    put:
      description: Updates the state of a temperature sensor 
      parameters: 
        - $ref: '#/parameters/UUID'
        - name: state
          in: body
          description: temperature sensor state
          schema:
            $ref: '#/definitions/State'
      responses:
        200:
          description: Successfully updated temperature sensor 
          $ref: '#/responses/headers'
        400:
          $ref: '#/responses/Error'
      x-lambda-function: state
    delete:
      description: Delete a temperature sensor by id
      parameters:
          - $ref: '#/parameters/UUID'
      responses:
        200:
          description: Successfully deleted temperature sensor 
          $ref: '#/responses/headers'
        400:
          $ref: '#/responses/Error'
      x-lambda-function: state
        
definitions:
  State:
    description: temperature sensor state
    type: object
    properties:
      uuid:
        type: string
      area:
        type: string
      temperature:
        type: integer
      temperature_scale:
        type: string
      update_period:
        type: integer          

parameters:
  UUID:
    name: uuid
    in: path
    type: string
    required: true
    description: Id of temperatureSensor

responses:
  headers:
    Access-Control-Allow-Headers:
      type: "string"
    Access-Control-Allow-Methods:
      type: "string"
    Access-Control-Allow-Origin:
      type: "string"
  Error:
    description: Invalid request error
    $ref: '#/responses/headers'    
    schema:
      type: object
      properties:
        message:
          type: string
          
x-lambda-functions:
  state:
    runtime: python3.6
    handler: state.lambda_handler
    memory: 128
    path_to_code: ./
  
    